### PR TITLE
[WIP] New design

### PR DESCRIPTION
**Pull request by jcrist**
New design using wrappers for scikit-learn estimators to provide common patterns. Two wrappers are implemented:

- `Averaged`: map fit across partitions, then average coefficients
- `Chained`: chain calls to `partial_fit` along for each partition

To use, just wrap a normal scikit-learn estimator:

```
clf = Averaged(sklearn.linear_model.LogisticRegression())
clf.fit(dask_X, dask_y)
```

By default this computes and mutates `clf`. As such, these can be dropped into scikit-learn pipelines and everything *should* just work. To compute lazily, pass `compute=False` to `fit`:

```
clf2 = clf.fit(dask_X, dask_y, compute=False)
```

Here `clf2` is not the same object as `clf`. This is to simplify reasoning about mutation when done lazily. To compute later, use the `compute` method:

```
clf2.compute()
clf2.compute()     # This is a no-op
```

This computes inplace, and returns itself as well. If there's nothing lazy to compute, this is a no-op.

Classes for `Pipeline`, `GridSearchCV`, and `RandomizedSearchCV` have also been implemented, using the same patterns described above. Note that the dask gridsearch only works with sklearn estimators, and not with dask estimators. With some work this should be doable, which would result in out-of-core cross validation capabilities.

Todo:
- [ ] Determine if this is a good idea
- [ ] Clean up horrible inconsistencies
- [ ] Tests
- [ ] Docs

### CODE REVIEW

**Comment by jcrist** [comment]
Two examples:

- Using `Chained` and `Averaged` for out-of-core text processing: http://nbviewer.jupyter.org/gist/jcrist/fcbfd9e3dc8ca00f4e5132ef02a9956d
- Using `GridSearchCV` and `Pipeline` for common subexpression elimination for grid search: http://nbviewer.jupyter.org/gist/jcrist/66616fa8adc8732b70d2bfd0f5adec85

**Comment by jcrist** [comment]
Keeping this moderately sane is proving difficult - I keep running into points where dask is running inside dask (which ends badly). A few thoughts that might make things more manageable (or more complicated, would need to try things out):

- No lazy classes allow mutation of the estimator (e.g. `clf2 = clf1.fit(X, y); assert clf2 is not clf1`). This would make reasoning about what's going on a lot easier for estimators that can be merged with the external world (single graph, non-iterative). Downside is they can't be passed into sklearn stuff by default, but that's honestly probably not a common workflow. Alternatively, the parallel models may not be that useful (unsure of usefulness), and could be ditched entirely.

- Separate the grid search/pipeline for many small models (all sklearn estimators) from the grid search for wrapping models parallelized with dask. The issue here is that the second can result in dask running inside dask, which almost always messes stuff up. This could also just be done with a switch in the class, I just need to do a better job of abstracting that out.

- Ditching the static-single-graph idea completely, and make distributed a dependency. The mix of paradigms (futures and graphs) may make writing the iterative algorithms simpler.

**Comment by mrocklin** [comment]
In the dasklearn experiment from long ago we followed the no-mutation rule and I generally found things to be sane.  I think that supporting nested computation by default is of more value that immediate sklearn support.  Alternatively maybe mutation is something that we wrap around as a compatibility later after we're done.  Everything is pure by default and then, when you want to drop into an existing sklearn pipeline you wrap `Inplace` around it or something.

@ogrisel this is nowhere near a high priority to anyone, but I'm curious how reasonable a request would it be to ask sklearn to eventually support "pure" models, e.g. changing code throughout the sklearn codebase as follows:

* Before: `est.fit(...)
* After: `est = est.fit(...)`

**Comment by mrocklin** [comment]
Should I be concerned by the lack of tests here?

**Comment by jcrist** [comment]
Not really, this branch is old. Things are being moved over to the new branch (with tests) as I get to them.

**Comment by ogrisel** [comment]
> @ogrisel this is nowhere near a high priority to anyone, but I'm curious how reasonable a request would it be to ask sklearn to eventually support "pure" models.

This is unlikely to ever happen, it would break the code of too many people.

However it's possible to do:

```python
>>> from copy import deepcopy()
>>> deepcopy(est).fit(...)
```

That should work as you want, no?

**Comment by mrocklin** [comment]
My thought was that sklearn estimators would still behave exactly the same, operating in place.  However SKLearn code wouldn't assume this and would instead replace instances like `est.fit(...)` with `est = est.fit(...)`.  This would allow pure estimators to be dropped into existing sklearn code.  This wouldn't cause any breaking changes to user code except if they start using new pure estimators from third party packages.

This is all premature though.  Just thinking.

**Pull request closed without merging**
